config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users

    root to: "users#index"
  end

  resources :users

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :matches

  resources :names

  resources :favorites

  resources :partnerships, only: [:new, :create]

  get "boy_names", to: "names#boy", as: "boy_names"
  get "girl_names", to: "names#girl", as: "girl_names"

root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.is_admin?
      # this gives the admin user super powers by enabling them to perform any action on any model.
      can :manage, :all
    end
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby.rb
class Baby < ApplicationRecord
  validates :name, presence: true
  validates :meaning, presence: true
  validates :gender, presence: true

  has_many :likes

  def self.find_by_couple(first_partner, second_partner)
    self.find_by_sql([%q/
        SELECT babies.* FROM babies
          INNER JOIN (
            SELECT baby_id FROM liked_names
            WHERE user_id = ?
              INTERSECT SELECT baby_id FROM liked_names
              WHERE user_id = ?
          ) as baby_ids
        ON babies.id = baby_ids.baby_id
      /, first_partner.id, second_partner.id
    ])
  end


end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/liked_name.rb
class LikedName < ApplicationRecord
  belongs_to :users
  belongs_to :babies
end

app/models/match.rb
class Match < ApplicationRecord
end

app/models/partnership.rb
class Partnership < ApplicationRecord
  belongs_to :user_one, class_name: "User"
  belongs_to :user_two, class_name: "User"
  has_many :users, dependent: :nullify

  delegate :email, to: :user_one, allow_nil: true, prefix: true
  delegate :email, to: :user_two, allow_nil: true, prefix: true

  # validates :email, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :liked_names
  belongs_to :partnership

  validates(:first_name, { presence: true })
  validates(:last_name, { presence: true })
  validates(:email, { presence: true, uniqueness: true })

  def partner
    return nil if partnership.blank?
    if partnership.user_one_id == self.id
      partnership.user_two
    else
      partnership.user_one
    end
  end

  def self.search(search_term)
    where(['first_name ILIKE ? OR last_name ILIKE ? OR email ILIKE ?', "%#{search_term}%", "%#{search_term}%", "%#{search_term}%"])
  end

  def self.created_after(date)
    where(['created_at > ?', "#{date}"])
  end

  def self.is_not(name)
    where('first_name != ? AND last_name != ?', "#{name}", "#{name}")
  end

  def full_name
    "#{first_name} #{last_name}".titleize
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!

  def index
    @boys = Baby.find_by_couple(*current_user.partnership.users).select { |baby| baby.gender == 'M' }
    @girls = Baby.find_by_couple(*current_user.partnership.users).select { |baby| baby.gender == 'F' }
  end
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  before_action :authenticate_user!
  before_action :like_baby

  def index
    # @page = params[:page] || 1
    # @boys = Baby.where(gender: 'M').order(:name).page(@page).per(1)
    # @girls = Baby.where(gender: 'F').order(:name).page(@page).per(1)
  end

  def boy
    @page = params[:page] || 1
    @boys = Baby.where(gender: 'M').order(:name).page(@page).per(1)
  end

  def girl
    @page = params[:page] || 1
    @girls = Baby.where(gender: 'F').order(:name).page(@page).per(1)
  end

  private

  def like_baby
    if params[:like] == 'true'
      liked_name = LikedName.new
      liked_name.user_id = current_user.id
      liked_name.baby_id = params[:baby_id]
      liked_name.save
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    @user = User.find_by_email(params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = 'Signed In!'
      redirect_to root_path
    else
      flash[:alert] = 'Could not sign in!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Signed Out!'
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User Created and Signed in!"
      redirect_to root_path
    else
      flash[:alert] = "Something Went Wrong!"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<br><br><br><br>
<section id="hero-area" >
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="block wow fadeInUp" data-wow-delay=".3s">

                    <!-- Slider -->
                    <section class="cd-intro">
                        <h1 class="wow fadeInUp animated cd-headline slide" data-wow-delay=".4s" >
                        <span>Welcome to NaMie</span><br>
                        <span class="cd-words-wrapper">
                            <b class="is-visible">LINK WITH YOUR PARTNER</b>
                            <b>CHOOSE NAMES YOU LIKE</b>
                            <b>SEE WHERE YOU MATCH!</b>
                        </span>
                        </h1>
                        </section> <!-- cd-intro -->
                        <!-- /.slider -->
                        <h2 class="wow fadeInUp animated" data-wow-delay=".6s" >
                            NaMie is an app to help you and your partner discover great names for your baby.<br> Take the stress out of naming and let NaMie help you decide on the perfect name,<br>With NaMie, you'll spend less time arguing and more time Name calling!
                        </h2>
                        <!-- <a class="btn-lines dark light wow fadeInUp animated smooth-scroll btn btn-default btn-green" data-wow-delay=".9s" href="" data-section="#works" >Get Started</a>
                        <a class="btn-lines dark light wow fadeInUp animated smooth-scroll btn btn-default btn-green" data-wow-delay=".9s" href="/names" data-section="#works" >Black Button</a> -->

                        <%= link_to "Get Started", names_path, class: "btn-lines dark light btn btn-default btn-green" %>

                        <!-- <%= link_to 'Name', names_path %> -->

                    </div>
                </div>
            </div>
        </div>
    </section><!--/#main-slider-->

app/views/names/boy.html.erb
<br>
<section id="feature">

  <div class="col-md-12 tab-content">
    <div id="boys" class="animated bounceInDown">
      <% @boys.each do |boy| %>
        <div class="col-md-offset-2 col-md-8 card" style= "border: thick solid grey; background-color: rgba(25, 136, 250, 0.66);">
          <hr>
          <h1 style="text-align: center; font-size: 60px; font-family: Lobster Two"><%= boy.name %></h1><hr><br>
          <p style="font-size: 20px; color: black;"><strong>Meaning and History: </strong><%= boy.meaning %></p><br>
          <p style="font-size: 20px; color: black;"><strong>Pronunciation: </strong><%= boy.pronounced %></p><br>
          <p style="font-size: 20px; color: black;"><strong>Related names/Variants: </strong><%= boy.related %></p><br>
          <p style="font-size: 20px; color: black;"><strong>Popularity: </strong>#<%= boy.popularity %></p><br>
        </div>
        <div class="row">
          <div class="container-fluid" style="justify-content: center; clear:both; width: 400px;">
            <%= link_to boy_names_path(page: (@page.to_i + 1), like: false) do %>
              <i class="ion-ios-close-outline user_dislike pull-left" id="nah" style='color:red'></i>
            <% end %>
            <%= link_to boy_names_path(page: (@page.to_i + 1), like: true, baby_id: boy.id) do %>
              <i class="ion-ios-checkmark-outline pull-right user_like" style='color: green'></i>
            <% end %>
          </div>
        </div>
        <br>
      <% end %>
    </div>
  </div>
</section>

app/views/names/girl.html.erb
<br>
<section id="feature">
  <div class="col-md-12">
    <div id="girls" class="animated bounceInDown">
      <% @girls.each do |girl| %>
        <div class="col-md-offset-2 col-md-8 card" style= "border: thick solid grey; background-color: pink;">
          <hr>
          <h1 style="text-align: center; font-size: 60px; font-family: Lobster Two"><%= girl.name %></h1><hr><br>
          <p style="font-size: 20px; color: black;"> <strong>Meaning and History: </strong><%= girl.meaning %></p><br>
          <p style="font-size: 20px; color: black;"><strong>Pronunciation: </strong><%= girl.pronounced %></p><br>
          <p style="font-size: 20px; color: black;"><strong>Related names/Variants: </strong><%= girl.related %></p><br>
          <p style="font-size: 20px; color: black;"> <strong>Popularity: </strong>#<%= girl.popularity %></p><br>
        </div>
        <div class="row">
          <div class="container-fluid" style="justify-content: center; clear:both; width: 400px;">
            <%= link_to girl_names_path(page: (@page.to_i + 1), like: false) do %>
              <i class="ion-ios-close-outline user_dislike pull-left" style='color:red'></i>
            <% end %>
            <%= link_to girl_names_path(page: (@page.to_i + 1), like: true, baby_id: girl.id) do %>
              <i class="ion-ios-checkmark-outline pull-right user_like" style='color: green'></i>
            <% end %>
          </div>
        </div>
        <br>
      <% end %>
    </div>
  </div>
</section>

app/views/names/index.html.erb
<br><br><br><br><br><br><br><br><br>
<div class='col-lg-12'>
  <div class='col-md-2'>
  </div>
  <div class='col-md-8' style="text-align: center;">
    <row>
      <h1 style="text-align: center; font-family: Lobster Two; font-size: 45px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;We're Expecting</h1><br><br>
    </row>
    <row>
    <%= link_to boy_names_path do %>
      <%= fa_icon "male 4x", style: "color: rgba(25, 136, 250, 0.66); font-size: 250px;", class: "fa-6x" %>
    <% end %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

    <%= link_to girl_names_path do %>
      <%= fa_icon "female 4x", style: "color: rgba(238, 56, 254, 0.68); font-size: 250px", class: "fa-6x-girl" %>
    <% end %>
  </row>
  <div class='col-md-2'>
  </div>
  </div>
</div>