config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users

    root to: "users#index"
  end

  resources :users

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :matches

  resources :names

  resources :favorites

  resources :partnerships, only: [:new, :create]

  get "boy_names", to: "names#boy", as: "boy_names"
  get "girl_names", to: "names#girl", as: "girl_names"

root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.is_admin?
      # this gives the admin user super powers by enabling them to perform any action on any model.
      can :manage, :all
    end
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby.rb
class Baby < ApplicationRecord
  validates :name, presence: true
  validates :meaning, presence: true
  validates :gender, presence: true

  has_many :likes

  def self.find_by_couple(first_partner, second_partner)
    self.find_by_sql([%q/
        SELECT babies.* FROM babies
          INNER JOIN (
            SELECT baby_id FROM liked_names
            WHERE user_id = ?
              INTERSECT SELECT baby_id FROM liked_names
              WHERE user_id = ?
          ) as baby_ids
        ON babies.id = baby_ids.baby_id
      /, first_partner.id, second_partner.id
    ])
  end


end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/liked_name.rb
class LikedName < ApplicationRecord
  belongs_to :users
  belongs_to :babies
end

app/models/match.rb
class Match < ApplicationRecord
end

app/models/partnership.rb
class Partnership < ApplicationRecord
  belongs_to :user_one, class_name: "User"
  belongs_to :user_two, class_name: "User"
  has_many :users, dependent: :nullify

  delegate :email, to: :user_one, allow_nil: true, prefix: true
  delegate :email, to: :user_two, allow_nil: true, prefix: true

  # validates :email, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :liked_names
  belongs_to :partnership

  validates(:first_name, { presence: true })
  validates(:last_name, { presence: true })
  validates(:email, { presence: true, uniqueness: true })

  def partner
    return nil if partnership.blank?
    if partnership.user_one_id == self.id
      partnership.user_two
    else
      partnership.user_one
    end
  end

  def self.search(search_term)
    where(['first_name ILIKE ? OR last_name ILIKE ? OR email ILIKE ?', "%#{search_term}%", "%#{search_term}%", "%#{search_term}%"])
  end

  def self.created_after(date)
    where(['created_at > ?', "#{date}"])
  end

  def self.is_not(name)
    where('first_name != ? AND last_name != ?', "#{name}", "#{name}")
  end

  def full_name
    "#{first_name} #{last_name}".titleize
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!

  def index
    @boys = Baby.find_by_couple(*current_user.partnership.users).select { |baby| baby.gender == 'M' }
    @girls = Baby.find_by_couple(*current_user.partnership.users).select { |baby| baby.gender == 'F' }
  end
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  before_action :authenticate_user!
  before_action :like_baby

  def index
    # @page = params[:page] || 1
    # @boys = Baby.where(gender: 'M').order(:name).page(@page).per(1)
    # @girls = Baby.where(gender: 'F').order(:name).page(@page).per(1)
  end

  def boy
    @page = params[:page] || 1
    @boys = Baby.where(gender: 'M').order(:name).page(@page).per(1)
  end

  def girl
    @page = params[:page] || 1
    @girls = Baby.where(gender: 'F').order(:name).page(@page).per(1)
  end

  private

  def like_baby
    if params[:like] == 'true'
      liked_name = LikedName.new
      liked_name.user_id = current_user.id
      liked_name.baby_id = params[:baby_id]
      liked_name.save
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User Created and Signed in!"
      redirect_to root_path
    else
      flash[:alert] = "Something Went Wrong!"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js">
  <head>
    <title>NaMie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag "application" %>
    <link href="https://fonts.googleapis.com/css?family=Acme" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster+Two" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cinzel" rel="stylesheet">


            <meta charset="utf-8">
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
            <link rel="icon" type="image/png" href="images/favicon.png">
            <title>NaMie</title>
            <meta name="description" content="">
            <meta name="keywords" content="">
            <meta name="author" content="">

   </head>

   <body>

     <header id="top-bar" class="navbar-fixed-top animated-header">
         <div class="container">
             <div class="navbar-header">
                 <!-- responsive nav button -->
                 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                 <span class="sr-only">Toggle navigation</span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 </button>
                 <!-- /responsive nav button -->

                 <!-- logo -->
                 <div class="navbar-brand" style="position: absolute; top:-35px; left:0">
                     <a href="/" >
                         <!-- <img src="assets/images/logo.png"> -->
                         <%= image_tag('namie.png', size: '140x140') %>
                     </a>
                 </div>
                 <!-- /logo -->
             </div>
             <!-- main menu -->
             <nav class="collapse navbar-collapse navbar-right" role="navigation" style="font-family: Acme;">
                 <div class="main-menu">
                     <ul class="nav navbar-nav navbar-right">
                         <li>
                             <a href="/" >Home</a>
                         </li>
                         <li><%= link_to "Names", names_path %></li>
                         <li><%= link_to "Matches", matches_path %></li>
                         <li><%= link_to "Link Account", new_partnership_path %></li>
                         <% if user_signed_in? %>
                         <% current_user = User.find_by_id session[:user_id] %>

                           <li><%= link_to 'Log Out', sessions_path, method: :delete %></li>
                         <% else %>
                           <li><a href="/users/new">Sign Up</a></li>
                           <li><a href="/sessions/new">Log In</a></li>
                         <% end %>
                     </ul>
                 </div>
             </nav>
             <!-- /main nav -->
         </div>
     </header>


    <% if flash[:notice] %>
      <div class="flash-notice"><%= flash[:notice] %></div>
    <% elsif flash[:alert] %>
      <div class="flash-alert"><%= flash[:alert] %></div>
    <% end %>

    <div class='container'>
      <%= yield %>
    </div><br><br><br><br><br>
    <!-- ==================================================
    Footer Section Start
    ================================================== -->
    <footer id="footer">
        <div class="container">
            <div class="col-md-8">
                <p class="copyright">Copyright: <span>2017</span> . Designed and Developed by Josh Gamble</p>
            </div>
            <div class="col-md-4">
                <!-- Social Media -->
                <ul class="social">
                    <li>
                        <a href="https://www.facebook.com/CunningLinguist83" class="Facebook">
                            <i class="ion-social-facebook"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://twitter.com/GamblesGames" class="Twitter">
                            <i class="ion-social-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.linkedin.com/in/josh-gamble" class="Linkedin">
                            <i class="ion-social-linkedin"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.youtube.com/user/VGElites" class="Google Plus">
                            <i class="ion-social-googleplus"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </footer> <!-- /#footer -->

</body>
</html>